-- Table: users
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    date_of_birth DATE NOT NULL,
    email VARCHAR(20) NULL,
    UNIQUE (phone),
    UNIQUE (email),
    PRIMARY KEY(id)
);

-- Table: roles
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR(20) NOT NULL,
    UNIQUE(role_name),
    PRIMARY KEY (id)
);

-- Table for mapping user and roles: user_roles
CREATE TABLE user_roles (
    user_id  INT NOT NULL,
    role_id  INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

/*-- Table: access
CREATE TABLE access (
                        id INT GENERATED BY DEFAULT AS IDENTITY,
                        user_id INT NOT NULL,
                        identification_number BIGINT NOT NULL,
                        access_status BOOLEAN NOT NULL,
                        UNIQUE (identification_number),
                        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                        PRIMARY KEY (id)
);*/

-- Table: access
CREATE TABLE access (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    UNIQUE (username),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (id)
);

-- Insert data

INSERT INTO users VALUES (1, 'Максим','Садовский', '+375(29)-575-64-10','24-11-2001','maksim_2411@mail.ru');
INSERT INTO users VALUES (2, 'Павел','Анищенко', '+375(29)-545-64-10','21-11-2001','pavel_2111@mail.ru');

INSERT INTO roles VALUES (1, 'ROLE_USER');
INSERT INTO roles VALUES (2, 'ROLE_ADMIN');

INSERT INTO user_roles VALUES (1,2);

INSERT INTO access VALUES (1, 1, 'admin', 'qwerty', true);
